name: sharemate
description: "ShareMate - A sharing platform for your FYP project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  image_picker: ^1.1.1
  firebase_storage: 13.0.3
  cached_network_image: ^3.2.4

  

  mobile_scanner: ^7.1.3
  permission_handler: ^11.3.0
  qr_flutter: ^4.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
